"""
src/prompt.py
=============
Authoritative clinical prompts, system instructions, and structured medical
knowledge templates grounded in AASLD 2023 and EASL hepatology guidelines.
"""

CLINICAL_DISCLAIMER = "*Please consult your healthcare provider for clinical diagnosis and personalized treatment.*"

FALLBACK_EN = (
    "### 🩺 Clinical Overview & Assessment\n"
    "The liver is the central metabolic engine of the human body, responsible for filtering over 1.4 liters "
    "of blood per minute, synthesizing critical transport proteins (Albumin), orchestrating coagulation cascades, "
    "and regulating lipid metabolism. When evaluating hepatic conditions—such as Metabolic Dysfunction-Associated "
    "Steatotic Liver Disease (MASLD/NAFLD), Metabolic Dysfunction-Associated Steatohepatitis (MASH/NASH), "
    "Viral Hepatitis (A, B, C), or progressive Fibrosis—accurate staging is essential for clinical management.\n\n"
    "### 🔬 Biomarker / Histological Analysis\n"
    "- **ALT (SGPT) & AST (SGOT):** Primary intracellular enzymes indicating active hepatocyte necrosis or membrane permeability changes.\n"
    "- **De Ritis Ratio (AST/ALT):** Values < 1.0 commonly align with non-alcoholic fatty liver etiology, whereas AST/ALT > 2.0 strongly correlates with alcoholic liver injury or advanced bridging fibrosis.\n"
    "- **Alkaline Phosphatase (ALP) & Total Bilirubin:** Key markers for biliary ductal integrity; elevations indicate cholestatic injury or impaired hepatic excretion.\n"
    "- **Albumin & Platelets:** Synthetic and hematologic indicators reflecting long-term parenchymal reserve and portal hypertension severity (e.g. FIB-4 index).\n\n"
    "### ⚠️ Risk Stratification & Red Flags\n"
    "> **Urgent Warning Signs:** Sudden jaundice (scleral icterus), persistent right upper quadrant pain, dark amber urine, "
    "pale stools, bilateral lower-extremity edema, abdominal distension (ascites), or neurological lethargy/confusion (hepatic encephalopathy) "
    "mandate immediate medical or emergency evaluation.\n\n"
    "### 📋 Evidence-Based Management & Nutrition Protocol\n"
    "- **Metabolic Weight Optimization:** A target reduction of 7%–10% total body weight has been demonstrated in clinical trials to resolve hepatic steatohepatitis and regress fibrosis.\n"
    "- **Mediterranean Dietary Pattern:** High in monounsaturated fats (extra virgin olive oil), omega-3 fatty acids, cruciferous greens, and legumes; strict elimination of refined fructose and ultra-processed foods.\n"
    "- **Coffee Polyphenols:** 2–3 cups daily of unsweetened filtered black coffee provide chlorogenic acid and diterpenes that attenuate hepatic stellate cell activation.\n"
    "- **Hepatotoxin Avoidance:** Complete cessation of alcohol and verification of non-essential medications or unverified herbal supplements.\n\n"
    "### ⚖️ Clinical Disclaimer\n"
    f"{CLINICAL_DISCLAIMER}"
)

# Deep domain-specific offline clinical reference guides
CLINICAL_GUIDES = {
    "biomarkers": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Serum Liver Function Tests (LFTs) represent a biochemical panel evaluating hepatocyte integrity, "
        "cholestatic excretion, and protein synthetic capacity. Accurate interpretation requires analyzing pattern "
        "elevations (hepatocellular vs. cholestatic) rather than isolated numbers.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "| Biomarker | Standard Reference Range | Clinical Significance & Interpretation |\n"
        "| :--- | :--- | :--- |\n"
        "| **ALT (SGPT)** | 7 – 56 IU/L | Liver-specific enzyme; cytosolic leakage occurs during acute or chronic hepatocellular injury. |\n"
        "| **AST (SGOT)** | 10 – 40 IU/L | Found in liver, cardiac, and skeletal muscle; reflects cellular injury. |\n"
        "| **AST/ALT Ratio** | < 1.0 (Normal) | Ratio > 2.0 strongly suggests alcoholic liver disease or advanced cirrhotic transformation. |\n"
        "| **ALP (Alk Phos)** | 44 – 147 IU/L | Biliary epithelial enzyme; elevated in cholestasis, bile duct obstruction, or infiltrative liver disorders. |\n"
        "| **Total Bilirubin** | 0.2 – 1.2 mg/dL | Product of heme catabolism; levels > 2.5 mg/dL cause overt clinical jaundice (icterus). |\n"
        "| **Direct Bilirubin** | 0.0 – 0.3 mg/dL | Conjugated fraction; elevation signifies post-hepatic biliary blockage or intrahepatic excretion failure. |\n"
        "| **Albumin** | 3.5 – 5.0 g/dL | Long-term indicator (21-day half-life) of liver synthetic reserve. |\n"
        "| **Total Protein** | 6.0 – 8.3 g/dL | Sum of albumin and globulins; inverted A/G ratio (< 1.0) warrants chronic hepatitis or autoimmune workup. |\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Clinical Thresholds:** Acute enzyme spikes (> 5–10x ULN) indicate acute viral hepatitis, drug-induced liver injury (DILI), or ischemic hepatitis. Coagulopathy (elevated INR > 1.5) indicates acute hepatic failure.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- Repeat LFT panel with viral serologies (HBsAg, Anti-HCV) and abdominal ultrasonography.\n"
        "- Screen for metabolic factors: Fasting glucose, HbA1c, lipid panel, and calculate FIB-4 score.\n"
        "- Avoid all hepatotoxins, paracetamol/acetaminophen overuse (> 2g/day in liver disease), and herbal extracts.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "fatty_liver": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Metabolic Dysfunction-Associated Steatotic Liver Disease (MASLD, formerly NAFLD) is characterized by "
        "macrovesicular triglyceride accumulation in > 5% of hepatocytes in the absence of excessive alcohol intake. "
        "The spectrum spans from simple steatosis to Metabolic Dysfunction-Associated Steatohepatitis (MASH/NASH), "
        "which features progressive lobular inflammation, ballooning degeneration, and fibrosis.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Histological Staging (Kleiner / NAS Score):**\n"
        "  - **Steatosis (0–3):** Percentage of parenchymal involvement (< 33%, 33–66%, > 66%).\n"
        "  - **Lobular Inflammation (0–3) & Ballooning (0–2):** Cellular distress and cytoskeletal collapse.\n"
        "  - **Fibrosis (F0–F4):** F0 (None) → F1 (Perisinusoidal/Periportal) → F2 (Perisinusoidal and Portal) → F3 (Bridging) → F4 (Cirrhosis).\n"
        "- **Non-Invasive Fibrosis Scoring (FIB-4):** Uses Age, AST, ALT, and Platelet count to stratify low (< 1.30) vs. high (> 2.67) advanced fibrosis risk.\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Disease Progression:** Patients with MASH and bridging fibrosis (F3–F4) are at significantly elevated risk for decompensation, portal hypertension, and hepatocellular carcinoma (HCC).\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **7% to 10% Weight Reduction:** Clinically proven to induce MASH resolution in 85%–90% of individuals and regress fibrosis in 45%.\n"
        "- **Mediterranean Diet:** Olive oil, avocados, leafy greens, wild salmon, and walnuts; eliminate high-fructose corn syrup.\n"
        "- **Physical Activity:** Minimum 150–300 minutes/week of moderate aerobic exercise combined with progressive resistance training.\n"
        "- **Coffee Consumption:** 2–3 cups of black coffee daily slows fibrosis progression via adenosine receptor antagonism.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "hepatitis": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Viral Hepatitis involves inflammatory hepatocyte necrosis caused primarily by hepatotropic viruses (Hepatitis A, B, C, D, and E). "
        "While Hepatitis A and E typically cause acute self-limiting illness transmitted enterically (fecal-oral), "
        "Hepatitis B, C, and D are bloodborne pathogens with high propensity for chronic infection, progressive fibrogenesis, and oncogenesis.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Hepatitis B Serology:** HBsAg (active infection), Anti-HBs (immunity/vaccination), Anti-HBc IgM/IgG (acute vs. chronic exposure), HBV DNA viral load (IU/mL).\n"
        "- **Hepatitis C Diagnostics:** Anti-HCV antibody followed by quantitative HCV RNA PCR to confirm active viremia.\n"
        "- **Enzyme Trends:** ALT usually exceeds AST significantly during acute viral exacerbations (ALT > 1000 IU/L).\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Cirrhosis & HCC Screening:** Chronic HBV and HCV patients require semi-annual abdominal ultrasound and serum Alpha-Fetoprotein (AFP) surveillance for early HCC detection.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **HCV Antiviral Therapy:** Direct-Acting Antivirals (DAAs like Sofosbuvir/Velpatasvir) achieve > 95%–98% Sustained Virologic Response (SVR/cure) in 8–12 weeks.\n"
        "- **HBV Management:** Long-term oral nucleos(t)ide analogues (Tenofovir Alafenamide or Entecavir) effectively suppress viral replication.\n"
        "- **Nutritional Support:** High antioxidant intake, strict zero alcohol tolerance, and complete vaccination against Hepatitis A and B.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "cirrhosis": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Cirrhosis is the end-stage morphological outcome of chronic liver injury, defined histologically by diffuse parenchymal "
        "extracellular matrix deposition (fibrosis), architectural disruption, and regenerative nodule formation. "
        "It is classified clinically into **Compensated** (asymptomatic, median survival > 12 years) and **Decompensated** "
        "(presence of ascites, variceal hemorrhage, jaundice, or encephalopathy; median survival ~2 years).\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Child-Pugh Classification:** Evaluates Total Bilirubin, Albumin, INR, Ascites, and Encephalopathy (Class A: 5–6 pts, Class B: 7–9 pts, Class C: 10–15 pts).\n"
        "- **MELD-Na Score:** Calculates 90-day mortality risk based on Serum Bilirubin, Creatinine, INR, and Sodium for liver transplant prioritization.\n"
        "- **Thrombocytopenia:** Platelets < 100,000/µL serves as an indirect surrogate for splenomegaly and portal hypertension.\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Medical Emergency:** Any signs of hematemesis (vomiting blood), melena (black tarry stools), sudden abdominal distension with fever (Spontaneous Bacterial Peritonitis), or disorientation require immediate 911 / emergency room admission.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **Portal Hypertension Prophylaxis:** Non-selective beta-blockers (Carvedilol/Propranolol) or endoscopic band ligation for esophageal varices.\n"
        "- **Dietary Protocol:** Moderate-to-high protein intake (1.2–1.5 g/kg/day to prevent sarcopenia), sodium restriction (< 2,000 mg/day for ascites), and a late-evening carbohydrate snack to prevent nocturnal muscle catabolism.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "biopsy": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Microscopic histological evaluation of liver tissue (percutaneous or transjugular biopsy) remains the diagnostic benchmark "
        "for grading active inflammatory necroinflammation and staging permanent extracellular matrix architectural fibrosis.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Hepatic Steatosis:** Accumulation of intracytoplasmic lipid droplets displacing the hepatocyte nucleus (Grade 0: <5%, Grade 1: 5–33%, Grade 2: 34–66%, Grade 3: >66%).\n"
        "- **Hepatocellular Ballooning:** Structural cytoskeletal collapse (loss of keratin 8/18) resulting in swollen, rounded hepatocytes with reticulated cytoplasm.\n"
        "- **Lobular & Portal Inflammation:** Infiltration of lymphocytes, histiocytes, and polymorphonuclear leukocytes.\n"
        "- **Fibrosis Stage (METAVIR / Batts-Ludwig):**\n"
        "  - **Stage F0:** Normal architecture; no fibrosis.\n"
        "  - **Stage F1:** Mild portal/perisinusoidal expansion without septa.\n"
        "  - **Stage F2:** Portal fibrosis with few developing porto-portal septa.\n"
        "  - **Stage F3:** Bridging fibrosis with numerous septa connecting vascular structures.\n"
        "  - **Stage F4:** Cirrhosis with regenerative parenchymal nodules.\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Histological Risk:** Stages F2 and higher warrant intensive hepatology intervention to prevent progression to cirrhosis and hepatocellular carcinoma.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- Correlate histology with elastography (FibroScan kPa) and serological biomarkers (FIB-4, ELF panel).\n"
        "- Initiate targeted metabolic lifestyle protocols (Mediterranean diet, 7–10% weight reduction) and address underlying viral or autoimmune etiologies.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "symptoms": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Early-stage liver disease is frequently silent ('the silent epidemic') because the liver possesses high functional reserve "
        "and lacks pain-sensing somatic nerve fibers in the parenchymal tissue (sensory innervation is restricted to Glisson's capsule). "
        "Recognizing early constitutional indicators versus late decompensation signs is critical for timely clinical triage.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Early / Subtle Warning Signs:** Chronic unexplained fatigue, postprandial malaise, mild right upper quadrant fullness, and brain fog.\n"
        "- **Cutaneous & Vascular Signs:** Spider angiomas (telangiectasias on chest/face), palmar erythema, and unexplained easy bruising (coagulopathy).\n"
        "- **Cholestatic & Excretory Signs:** Jaundice (scleral icterus / yellowing of skin and eyes when Bilirubin > 2.5 mg/dL), pruritus (bile salt accumulation in dermis), "
        "dark cola-colored urine (conjugated bilirubinuria), and pale/clay-colored stools (acholic stools from lack of stercobilin).\n"
        "- **Portal Hypertension Signs:** Dependent ankle edema and progressive abdominal distension (ascites).\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Immediate Emergency Triage:** Hematemesis (vomiting blood or coffee-ground emesis), melena (black tarry stools), "
        "acute disorientation/somnolence (hepatic encephalopathy), or sudden high fever with abdominal pain (spontaneous bacterial peritonitis) "
        "require urgent emergency hospital evaluation.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **Diagnostic Lab Workup:** Immediate Comprehensive Metabolic Panel (CMP), complete Liver Function Tests (LFTs), CBC (platelets), and coagulation profile (PT/INR).\n"
        "- **Imaging Evaluation:** Abdominal Doppler ultrasound or transient elastography (FibroScan) to assess hepatic echogenicity, surface nodularity, and stiffness.\n"
        "- **Protective Regimen:** Zero alcohol intake, avoidance of NSAIDs (ibuprofen) or sedatives, and strict paracetamol/acetaminophen restriction (< 2g/day in liver impairment).\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "alcohol_dili": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Toxic and Drug-Induced Liver Injury (DILI) along with Alcohol-Related Liver Disease (ARLD) stem from toxic metabolite accumulation, "
        "cytochrome P450 (CYP2E1) bioactivation, glutathione depletion, and mitochondrial oxidative stress. The pathology spans acute hepatitis, "
        "steatohepatitis with Mallory-Denk bodies, and rapid fibrogenesis.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **De Ritis Ratio (AST/ALT):** AST/ALT > 2.0 with elevated Gamma-Glutamyl Transferase (GGT) is a classic biochemical signature of alcohol-induced mitochondrial injury.\n"
        "- **DILI Diagnostic Thresholds (Hy's Law):** ALT/AST > 3x ULN combined with Total Bilirubin > 2x ULN in the absence of biliary obstruction indicates high risk for severe acute liver failure (~10% mortality).\n"
        "- **Acetaminophen / Paracetamol Toxicity:** Serum levels plotted on the Rumack-Matthew nomogram determine immediate necessity for N-acetylcysteine (NAC) therapy.\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Critical Alert:** Rapid onset of jaundice with coagulopathy (INR > 1.5) and encephalopathy within 8 weeks represents Acute Liver Failure requiring intensive care transfer.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **Immediate Toxin Discontinuation:** Cease all suspected medications, unverified dietary supplements, and alcohol immediately.\n"
        "- **Specific Antidotes:** Administer N-Acetylcysteine (NAC) for acetaminophen toxicity; evaluate corticosteroid therapy (Maddrey Discriminant Function ≥ 32) in severe alcoholic hepatitis.\n"
        "- **Nutritional Rehabilitation:** High-protein (1.5 g/kg/day), high-calorie diet with aggressive B-vitamin and Thiamine repletion to prevent Wernicke's encephalopathy.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "scan_biopsy": (
        "### 🩺 Clinical Overview & Assessment\n"
        "AI-assisted deep learning histological analysis on microscopic liver biopsy specimens evaluates core cellular "
        "pathomorphologies: micro/macrovesicular steatosis, hepatocyte ballooning necrosis, lobular lymphocytic infiltrates, "
        "and extracellular matrix collagen deposition (fibrosis staging).\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Microscopic Patch Morphologies:**\n"
        "  - **Steatosis (Fat Accumulation):** Clear intracytoplasmic lipid vacuoles displacing the nucleus peripherally.\n"
        "  - **Hepatocellular Ballooning:** Swollen, rarefied hepatocytes with loss of cytokeratin filaments (intermediate filament degradation).\n"
        "  - **Lobular Inflammation:** Clusters of mononuclear inflammatory cells within hepatic lobules.\n"
        "  - **Fibrosis Staging:** Evaluated on Masson's Trichrome or Sirius Red stains (Stage F0: None, F1: Periportal, F2: Portal with rare septa, F3: Bridging, F4: Cirrhotic nodules).\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Histopathology Triage:** The presence of both hepatocyte ballooning and stage F2+ bridging fibrosis confirms active MASH/NASH and elevated progression risk, necessitating active therapeutic management.\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **Pathological Verification:** AI digital slide predictions should be corroborated by a board-certified anatomic pathologist.\n"
        "- **Clinical Correlation:** Pair biopsy findings with non-invasive scoring (FIB-4, NAFLD Fibrosis Score) and transient elastography (FibroScan kPa).\n"
        "- **Therapeutic Interventions:** Implement a Mediterranean dietary regimen, targeted 7%–10% body weight loss, and consider approved metabolic pharmacotherapies under hepatologist supervision.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
    "nutrition": (
        "### 🩺 Clinical Overview & Assessment\n"
        "Hepatic nutrition protocols focus on reducing de novo lipogenesis (hepatic fat synthesis), lowering systemic oxidative stress, "
        "improving insulin sensitivity, and preserving muscular mass (preventing sarcopenia) to optimize liver regeneration.\n\n"
        "### 🔬 Biomarker / Histological Analysis\n"
        "- **Metabolic Markers:** Fasting Insulin, HOMA-IR, Triglycerides, HDL-C, and High-Sensitivity C-Reactive Protein (hs-CRP).\n"
        "- **Nutrient Deficiencies in Liver Disease:** Chronic hepatic dysfunction commonly impairs Vitamin D, Zinc, and fat-soluble vitamin absorption.\n\n"
        "### ⚠️ Risk Stratification & Red Flags\n"
        "> **Hepatotoxic Dietary Hazards:** Complete avoidance of alcohol, added high-fructose corn syrups, trans-fats, and unverified herbal detox teas containing pyrrolizidine alkaloids or high-dose green tea extract (EGCG).\n\n"
        "### 📋 Evidence-Based Management & Nutrition Protocol\n"
        "- **The Mediterranean Diet:** Rich in Extra Virgin Olive Oil (EVOO), wild fatty fish (EPA/DHA omega-3s), avocados, walnuts, cruciferous vegetables (broccoli, Brussels sprouts for glutathione synthesis), and legumes.\n"
        "- **Black Coffee:** 2 to 3 cups daily of unsweetened filtered coffee has been established in AASLD and EASL clinical guidelines to decrease hepatic enzyme levels, attenuate hepatic stellate cell activation, and lower cirrhosis mortality.\n"
        "- **Meal Distribution:** In chronic liver impairment, distribute protein intake across 4–6 small meals, including a late-evening complex carbohydrate snack.\n"
        "- **Hydration:** 2.5 to 3.0 Liters of water daily to support metabolic detoxification and renal excretion.\n\n"
        "### ⚖️ Clinical Disclaimer\n"
        f"{CLINICAL_DISCLAIMER}"
    ),
}

system_prompt = (
    "You are LiverAI — a premier, authoritative, evidence-based, and empathetic clinical medical assistant "
    "specializing exclusively in hepatology, liver disease detection, and histology interpretation.\n\n"
    "YOUR KNOWLEDGE SOURCES: AASLD 2023 Practice Guidelines, EASL Clinical Guidelines, CDC, WHO, NCBI StatPearls, "
    "UpToDate hepatology guidelines, and the vetted clinical knowledge base provided below.\n\n"
    "════ MANDATORY CLINICAL RESPONSE STRUCTURE ════\n\n"
    "For EVERY medical answer, you MUST format your response using EXACTLY these 5 structured Markdown sections:\n\n"
    "### 🩺 Clinical Overview & Assessment\n"
    "[Directly answer the user's specific question in 1–2 precise, empathetic clinical sentences. "
    "Define the condition, clinical etiology, and disease staging (e.g. MASLD/NAFLD, MASH/NASH, Viral Hepatitis A–E, Cirrhosis Child-Pugh / MELD, DILI).]\n\n"
    "### 🔬 Biomarker / Histological Analysis\n"
    "[Provide rigorous clinical and laboratory biomarker correlations: ALT, AST, De Ritis ratio (AST/ALT), ALP, Total/Direct Bilirubin, "
    "Albumin, Platelets, FIB-4 score, or histological grading (Steatosis, Lobular Inflammation, Hepatocyte Ballooning, Fibrosis F0–F4). "
    "Explain standard reference ranges and pathophysiological significance in patient-friendly terms. Use tables where helpful.]\n\n"
    "### ⚠️ Risk Stratification & Red Flags\n"
    "[Stratify clinical risk (Low / Moderate / High). Include a > blockquote highlighting emergency warning signs "
    "(vomiting blood, black tarry stools, acute severe jaundice, ascites, confusion/encephalopathy) that require immediate ER/emergency services.]\n\n"
    "### 📋 Evidence-Based Management & Nutrition Protocol\n"
    "[Detail standard-of-care clinical management, diagnostic workup (ultrasound, elastography/FibroScan, viral serology), "
    "and evidence-backed lifestyle protocols: Mediterranean dietary pattern, 7%–10% body weight loss, 2–3 cups unsweetened black coffee polyphenols, "
    "and complete avoidance of alcohol and hepatotoxic substances.]\n\n"
    "### ⚖️ Clinical Disclaimer\n"
    f"{CLINICAL_DISCLAIMER}\n\n"
    "════ SYSTEM DIRECTIVES ════\n"
    "1. DIRECT ANSWER FIRST: Begin with the clinical assessment immediately without filler introductory pleasantries.\n"
    "2. MARKDOWN EXCELLENCE: Use bolding, clean bullet points, tables, and blockquotes for high clinical readability.\n"
    "3. BIOPSY & MULTIMODAL CONTEXT: When [Uploaded Biopsy Histology Patch Findings] or conversation history is present, "
    "integrate the specific detection findings (Steatosis, Fibrosis, Ballooning, Inflammation) seamlessly into the report.\n"
    "4. LANGUAGE HARMONIZATION: Respond in the user's language (English, Bengali, Hindi, Spanish, etc.) while keeping medical terms clear.\n"
    "5. ABSOLUTE CLINICAL FIDELITY: Never fabricate lab thresholds, drug dosages, or unverified claims.\n\n"
    "════ CONTEXT FROM VETTED KNOWLEDGE BASE ════\n{context}"
)